# Generated by Django 5.0.2 on 2024-03-02 13:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id_employe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_employe', models.CharField(max_length=50)),
                ('email_employe', models.CharField(max_length=30)),
                ('telephone', models.BigIntegerField()),
                ('bureau', models.CharField(max_length=20)),
                ('matricule', models.BigIntegerField()),
                ('etat_employe', models.CharField(max_length=30)),
                ('poste', models.CharField(choices=[('1', 'President Directeur Générale'), ('2', 'Directeur Générale'), ('3', 'Assistant'), ('4', 'Consultant'), ('7', 'Chef Stucture'), ('8', 'Admin Projets'), ('9', 'Ingénieur D Etudes'), ('10', 'Chargé D Etudes '), ('11', 'Exploitant '), ('12', 'Exécutant '), ('13', 'Chef Projet'), ('14', 'Chef Partie')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='EtatProjet',
            fields=[
                ('id_etat', models.AutoField(primary_key=True, serialize=False)),
                ('lib_etat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaitreOuvrage',
            fields=[
                ('id_mouvrage', models.AutoField(primary_key=True, serialize=False)),
                ('lib_mouvrage', models.CharField(max_length=30)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marchet',
            fields=[
                ('id_marchet', models.AutoField(primary_key=True, serialize=False)),
                ('lib_marchet', models.CharField(max_length=30)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'information'), ('2', 'avertissement'), ('3', 'problème')], max_length=1)),
                ('titre', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SuiviTache',
            fields=[
                ('id_suivi', models.AutoField(primary_key=True, serialize=False)),
                ('date_suivi', models.DateField(default=datetime.datetime.now)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id_incident', models.AutoField(primary_key=True, serialize=False)),
                ('nom_incident', models.CharField(max_length=30)),
                ('date_incident', models.DateField(default=datetime.datetime.now)),
                ('pourcentage', models.FloatField()),
                ('progress', models.FloatField()),
                ('agentDeclencheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='notification',
            field=models.ManyToManyField(to='Gestion_projet.notification'),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.AutoField(primary_key=True, serialize=False)),
                ('nom_projet', models.CharField(max_length=30)),
                ('date_debut', models.DateField(default=datetime.datetime.now)),
                ('date_fin', models.DateField(default=datetime.datetime.now)),
                ('details', models.TextField()),
                ('progress', models.FloatField()),
                ('chefProjet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chef_de_Projet', to='Gestion_projet.employe')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.etatprojet')),
                ('maitreOuvrage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_projet.maitreouvrage')),
                ('marchet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.marchet')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='projet',
            field=models.ManyToManyField(to='Gestion_projet.projet'),
        ),
        migrations.CreateModel(
            name='SuiviIncident',
            fields=[
                ('id_suivi', models.AutoField(primary_key=True, serialize=False)),
                ('date_suivi', models.DateField(default=datetime.datetime.now)),
                ('details', models.TextField()),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.incident')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='suiviIncident',
            field=models.ManyToManyField(to='Gestion_projet.suiviincident'),
        ),
        migrations.AddField(
            model_name='employe',
            name='suiviTache',
            field=models.ManyToManyField(to='Gestion_projet.suivitache'),
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id_tache', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tache', models.CharField(max_length=30)),
                ('date_debut', models.DateField(default=datetime.datetime.now)),
                ('date_fin', models.DateField(default=datetime.datetime.now)),
                ('pourcentage', models.FloatField()),
                ('progress', models.FloatField()),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.projet')),
                ('sous_tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_tache+', to='Gestion_projet.tache')),
            ],
        ),
        migrations.AddField(
            model_name='suivitache',
            name='tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.tache'),
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id_ressource', models.AutoField(primary_key=True, serialize=False)),
                ('lib_ressource', models.CharField(max_length=30)),
                ('marque_ressource', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('1', 'Matériel de Transport'), ('2', 'Matériel pour le Diagnostic'), ('3', 'Matériel pour le Mesure'), ('4', 'Matériel de Nettoyage'), ('5', 'Matériel pour gros oeuvre'), ('6', 'Matériel pour second oeuvre'), ('7', 'Matériel pour Espace verts'), ('8', 'Matériel pour Industrie'), ('9', 'Matériel de Manutention'), ('10', 'Matériel de Signalisation'), ('11', 'Matériel portatif'), ('12', 'Engins de Terrasement'), ('13', 'Machines à Projete'), ('14', 'Electricité sur chantiers'), ('15', 'Autre')], max_length=2)),
                ('etat', models.CharField(choices=[('1', 'Bonne Etat '), ('2', 'Endomagé'), ('3', 'En Panne')], max_length=2)),
                ('disponibilite', models.CharField(choices=[('1', 'Disponible'), ('2', 'Louer'), ('3', 'En Panne')], max_length=2)),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.tache')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('titre', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('doc', models.FileField(default=None, upload_to='pdfs/')),
                ('details', models.TextField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.projet')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.tache')),
            ],
        ),
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('id_comission', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('details', models.TextField()),
                ('type', models.CharField(choices=[('1', 'CE'), ('2', 'CPREG')], max_length=2)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.projet')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.tache')),
            ],
        ),
        migrations.CreateModel(
            name='TacheRessource',
            fields=[
                ('id_TR', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField(default=datetime.datetime.now)),
                ('date_fin', models.DateField(default=datetime.datetime.now)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.ressource')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.tache')),
            ],
        ),
    ]
