# Generated by Django 5.0.2 on 2024-03-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='notification',
            field=models.ManyToManyField(blank=True, to='Gestion_projet.notification'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='projet',
            field=models.ManyToManyField(blank=True, to='Gestion_projet.projet'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='suiviIncident',
            field=models.ManyToManyField(blank=True, to='Gestion_projet.suiviincident'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='suiviTache',
            field=models.ManyToManyField(blank=True, to='Gestion_projet.suivitache'),
        ),
    ]
