# Generated by Django 5.0.2 on 2024-03-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0002_alter_employe_notification_alter_employe_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='progress',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
