# Generated by Django 5.0.2 on 2024-03-02 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0003_alter_projet_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='etat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_projet.etatprojet'),
        ),
    ]
