# Generated by Django 5.0.2 on 2024-03-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0004_alter_projet_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.BigIntegerField(unique=True),
        ),
    ]
