# Generated by Django 5.0.2 on 2024-03-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0007_alter_tache_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='pourcentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
