# Generated by Django 5.0.2 on 2024-03-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0008_alter_tache_pourcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email_employe',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
