# Generated by Django 5.0.2 on 2024-03-24 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0009_alter_employe_email_employe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='notification',
        ),
        migrations.AddField(
            model_name='employe',
            name='notificationNotSeen',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='employe',
            field=models.ManyToManyField(blank=True, to='Gestion_projet.employe'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='projet',
            field=models.ManyToManyField(blank=True, related_name='employes', to='Gestion_projet.projet'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('1', 'Information'), ('2', 'Avertissement'), ('3', '¨Problème')], max_length=1),
        ),
        migrations.CreateModel(
            name='NotificationSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
