# Generated by Django 5.0.2 on 2024-03-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0010_remove_employe_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('1', 'Information'), ('2', 'Avertissement'), ('3', 'Problème')], max_length=1),
        ),
    ]
