# Generated by Django 5.0.2 on 2024-03-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0011_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='employe',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='Gestion_projet.employe'),
        ),
    ]
