# Generated by Django 5.0.2 on 2024-03-24 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0013_employe_incidentnotseen_incidentseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='employe',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='Gestion_projet.employe'),
        ),
        migrations.AddField(
            model_name='incident',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.projet'),
        ),
        migrations.AddField(
            model_name='tache',
            name='employe',
            field=models.ManyToManyField(blank=True, related_name='taches', to='Gestion_projet.employe'),
        ),
    ]
