# Generated by Django 5.0.2 on 2024-03-25 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0014_incident_employe_incident_projet_tache_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
