# Generated by Django 5.0.2 on 2024-03-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0016_etatprojet_date_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='employe',
            field=models.ManyToManyField(blank=True, related_name='projets', to='Gestion_projet.employe'),
        ),
    ]
