# Generated by Django 5.0.2 on 2024-03-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0017_remove_employe_projet_projet_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
