# Generated by Django 5.0.2 on 2024-03-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0018_alter_projet_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='pourcentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tache',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
