# Generated by Django 5.0.2 on 2024-03-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0019_alter_tache_pourcentage_alter_tache_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.projet'),
        ),
    ]
