# Generated by Django 5.0.2 on 2024-03-28 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0022_alter_projet_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='progress',
        ),
        migrations.AlterField(
            model_name='tache',
            name='progress',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
