# Generated by Django 5.0.2 on 2024-03-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0024_projet_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='old_employe_emails',
            field=models.TextField(blank=True),
        ),
    ]
