# Generated by Django 5.0.2 on 2024-03-30 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0025_notification_old_employe_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='old_employe_emails',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='etat',
        ),
        migrations.AddField(
            model_name='etatprojet',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etat', to='Gestion_projet.projet'),
        ),
    ]
