# Generated by Django 5.0.2 on 2024-03-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0026_remove_notification_old_employe_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='latest_etat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
