# Generated by Django 5.0.2 on 2024-03-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0027_projet_latest_etat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TacheRessource',
            new_name='AffectationRessource',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='tache',
        ),
    ]
