# Generated by Django 5.0.2 on 2024-03-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0028_rename_tacheressource_affectationressource_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AffectationRessource',
            new_name='TacheRessource',
        ),
    ]
