# Generated by Django 5.0.2 on 2024-03-30 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0029_rename_affectationressource_tacheressource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='suiviIncident',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='suiviTache',
        ),
        migrations.AddField(
            model_name='suiviincident',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suiviIncident', to='Gestion_projet.employe'),
        ),
        migrations.AddField(
            model_name='suivitache',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suiviTache', to='Gestion_projet.employe'),
        ),
        migrations.AlterField(
            model_name='suiviincident',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.incident'),
        ),
        migrations.AlterField(
            model_name='suivitache',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suiviTache', to='Gestion_projet.tache'),
        ),
    ]
