# Generated by Django 5.0.2 on 2024-04-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0030_remove_employe_suiviincident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('1', 'President Directeur Générale'), ('2', 'Directeur Générale'), ('3', 'Assistant'), ('4', 'Consultant'), ('7', 'Chef Stucture'), ('8', 'Admin Projets'), ('9', 'Ingénieur D Etudes'), ('10', 'Chargé D Etudes '), ('11', 'Exploitant '), ('12', 'Exécutant '), ('13', 'Chef Projet'), ('14', 'Chef Tache')], max_length=3),
        ),
    ]
