# Generated by Django 5.0.2 on 2024-04-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0031_alter_employe_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='comission',
            name='employes',
            field=models.ManyToManyField(blank=True, null=True, related_name='comissions', to='Gestion_projet.employe'),
        ),
        migrations.AddField(
            model_name='comission',
            name='president',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.employe'),
        ),
        migrations.AddField(
            model_name='comission',
            name='titre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='employe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.employe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comission',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_projet.projet'),
        ),
    ]
