# Generated by Django 5.0.2 on 2024-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0032_comission_employes_comission_president_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='employes',
            field=models.ManyToManyField(related_name='comissions', to='Gestion_projet.employe'),
        ),
    ]
