# Generated by Django 5.0.2 on 2024-04-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0033_alter_comission_employes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comission',
            name='PV',
            field=models.FileField(default=None, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='employes',
            field=models.ManyToManyField(blank=True, related_name='comissions', to='Gestion_projet.employe'),
        ),
    ]
