# Generated by Django 5.0.2 on 2024-04-02 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0038_alter_tache_type_checktache'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktache',
            name='employe',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='checktaches', to='Gestion_projet.employe'),
        ),
    ]
