# Generated by Django 5.0.2 on 2024-04-03 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0039_checktache_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='chef_tache',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chef_taches', to='Gestion_projet.employe'),
            preserve_default=False,
        ),
    ]
