# Generated by Django 5.0.2 on 2024-04-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0041_alter_tache_chef_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='tache',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='Gestion_projet.tache'),
        ),
    ]
