# Generated by Django 5.0.2 on 2024-04-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0043_alter_suivitache_employe_alter_suivitache_tache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivitache',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suiviTache', to='Gestion_projet.employe'),
        ),
        migrations.AlterField(
            model_name='suivitache',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suiviTache', to='Gestion_projet.tache'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='tache_mere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_taches', to='Gestion_projet.tache'),
        ),
    ]
