# Generated by Django 5.0.2 on 2024-04-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0044_alter_suivitache_employe_alter_suivitache_tache_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='tache_mere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sous_taches', to='Gestion_projet.tache'),
        ),
    ]
