# Generated by Django 5.0.2 on 2024-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0046_alter_tache_tache_mere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='type',
            field=models.CharField(choices=[('1', 'Tâche simple'), ('2', 'Tâche besoin d un suivi ')], default='2', max_length=10),
        ),
    ]
