# Generated by Django 5.0.2 on 2024-04-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0047_alter_tache_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktache',
            name='employe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checktaches', to='Gestion_projet.employe'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='president',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_projet.employe'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_projet.tache'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='agentDeclencheur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_projet.employe'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='marchet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_projet.marchet'),
        ),
        migrations.AlterField(
            model_name='suivitache',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suiviTache', to='Gestion_projet.employe'),
        ),
        migrations.AlterField(
            model_name='suivitache',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suiviTache', to='Gestion_projet.tache'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='chef_tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_taches', to='Gestion_projet.employe'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='sous_tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_tache+', to='Gestion_projet.tache'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='tache_mere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_taches', to='Gestion_projet.tache'),
        ),
    ]
