# Generated by Django 5.0.2 on 2024-04-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0048_alter_checktache_employe_alter_comission_president_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comission',
            name='titre',
            field=models.CharField(max_length=30),
        ),
    ]
