# Generated by Django 5.0.2 on 2024-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0049_incident_details_tache_details_alter_comission_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='sous_tache',
        ),
        migrations.AddField(
            model_name='tache',
            name='sous_tache',
            field=models.ManyToManyField(blank=True, null=True, related_name='sous_tache+', to='Gestion_projet.tache'),
        ),
    ]
