# Generated by Django 5.0.2 on 2024-04-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0052_alter_tache_sous_tache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='sous_tache',
            field=models.ManyToManyField(blank=True, related_name='tache_mere+', to='Gestion_projet.tache'),
        ),
    ]
