# Generated by Django 5.0.2 on 2024-04-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0053_alter_tache_sous_tache'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tache_mere_through', to='Gestion_projet.tache')),
                ('tache_mere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_taches_through', to='Gestion_projet.tache')),
            ],
        ),
    ]
