# Generated by Django 5.0.2 on 2024-04-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0054_tacherelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TacheRelation',
        ),
    ]
