# Generated by Django 5.0.2 on 2024-04-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0055_delete_tacherelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='sous_tache',
        ),
    ]
