# Generated by Django 5.0.2 on 2024-04-29 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0056_remove_tache_sous_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='avancement',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='etatprojet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etat', to='Gestion_projet.projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='marchet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet', to='Gestion_projet.marchet'),
        ),
    ]
