# Generated by Django 5.0.2 on 2024-05-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0057_projet_avancement_alter_etatprojet_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='etat_employe',
            field=models.CharField(choices=[('1', 'Célibataire'), ('2', 'Mariée')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('1', 'President Directeur Générale'), ('2', 'Directeur Générale'), ('3', 'Assistant'), ('4', 'Consultant'), ('7', 'Chef Stucture'), ('8', 'Admin Projets'), ('9', 'Ingénieur D Etudes'), ('10', 'Chargé D Etudes '), ('11', 'Exploitant '), ('12', 'Exécutant '), ('13', 'Chef Projet'), ('14', 'Chef Tache'), ('15', 'Autre')], max_length=3),
        ),
        migrations.AlterField(
            model_name='notification',
            name='titre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projet',
            name='avancement',
            field=models.CharField(choices=[('1', 'normal'), ('2', 'bien'), ('3', ' trés bien'), ('4', 'mauvaise'), ('5', 'trés mauvaise'), ('6', 'pas encore commencé')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nom_projet',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='Gestion_projet.projet'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='type',
            field=models.CharField(choices=[('1', 'Tâche simple'), ('2', 'Tâche besoin d un suivi')], default='2', max_length=10),
        ),
    ]
