# Generated by Django 5.0.2 on 2024-05-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0058_alter_employe_etat_employe_alter_employe_poste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='Gestion_projet.projet'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('1', 'President Directeur Générale'), ('2', 'Directeur Générale'), ('3', 'Assistant'), ('4', 'Consultant'), ('5', 'Chef Stucture'), ('6', 'Ingénieur d informatique'), ('7', 'Ingénieur D Etudes'), ('8', 'Chargé D Etudes '), ('9', 'Exploitant '), ('10', 'Exécutant '), ('11', 'Chef Projet'), ('12', 'Chef Tache'), ('13', 'Autre')], max_length=3),
        ),
    ]
