# Generated by Django 5.0.2 on 2024-05-05 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0059_alter_comission_projet_alter_employe_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='avancement',
            field=models.CharField(choices=[('1', 'normal'), ('2', 'bien'), ('3', 'trés bien'), ('4', 'mauvaise'), ('5', 'trés mauvaise'), ('6', 'pas encore commencé'), ('7', 'Terminé')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='projet',
            name='avancement',
            field=models.CharField(choices=[('1', 'normal'), ('2', 'bien'), ('3', 'trés bien'), ('4', 'mauvaise'), ('5', 'trés mauvaise'), ('6', 'pas encore commencé'), ('7', 'Terminé')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='projet',
            name='chefProjet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_chef', to='Gestion_projet.employe'),
        ),
    ]
