# Generated by Django 5.0.2 on 2024-05-15 21:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0060_tache_avancement_alter_projet_avancement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='tache',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='Gestion_projet.tache'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='etat',
            field=models.CharField(choices=[('1', 'Bonne Etat'), ('2', 'Endomagé'), ('3', 'En Panne')], max_length=2),
        ),
        migrations.CreateModel(
            name='UtilisationRessource',
            fields=[
                ('id_TR', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField(default=datetime.datetime.now)),
                ('date_fin', models.DateField(default=datetime.datetime.now)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='util_ressource', to='Gestion_projet.ressource')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='util_ressource', to='Gestion_projet.tache')),
            ],
        ),
        migrations.DeleteModel(
            name='TacheRessource',
        ),
    ]
