# Generated by Django 5.0.2 on 2024-05-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0061_alter_incident_tache_alter_ressource_etat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckTache',
            new_name='EtatTache',
        ),
    ]
