# Generated by Django 5.0.2 on 2024-05-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0062_rename_checktache_etattache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='type',
            field=models.CharField(choices=[('1', 'CME'), ('2', 'COP'), ('2', 'CEO')], max_length=30),
        ),
    ]
