# Generated by Django 5.0.2 on 2024-05-31 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0064_alter_comission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatprojet',
            name='date_etat',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
