# Generated by Django 5.0.2 on 2024-06-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0068_alter_etattache_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('1', 'President Directeur Générale'), ('2', 'Directeur Générale'), ('3', 'Assistant'), ('4', 'Consultant'), ('5', 'Chef Stucture'), ('6', 'Ingénieur d informatique'), ('7', 'Ingénieur D Etudes'), ('8', 'Chargé D Etudes '), ('9', 'Exploitant '), ('10', 'Ingénieur de Génie Civile'), ('11', 'Chef Projet'), ('12', 'Chef Tache'), ('13', 'Autre')], max_length=3),
        ),
        migrations.AlterField(
            model_name='incident',
            name='nom_incident',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tache',
            name='nom_tache',
            field=models.CharField(max_length=60),
        ),
    ]
