# Generated by Django 5.0.2 on 2024-06-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_projet', '0069_alter_employe_poste_alter_incident_nom_incident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
